### ISSUE TITLE
Create test case for backwards compatibility with iMOD 5

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#368]
In GitLab by @JoerivanEngelen on May 15, 2023, 17:35

Create test case to test developments against. Probably good to use a clipped and converted IBRAHYM model for this.

### Tasks
- [ ] https://github.com/Deltares/imod-python/issues/450
- [ ] https://github.com/Deltares/imod-python/issues/451
- [ ] https://github.com/Deltares/imod-python/issues/453
- [ ] https://github.com/Deltares/imod-python/issues/454

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on May 25, 2023, 15:56

Frans sent me two models to test against.
These probably have to be cleaned up a bit to get a functional test case. For example, the .prj file contains absolute paths, which need to be replaced.

[c01_Model01.zip](https://gitlab.com/deltares/imod/imod-python/uploads/95c146f359547f1be411e1ca64951b1a/c01_Model01.zip)
[c02_Ibrahym_01.zip](https://gitlab.com/deltares/imod/imod-python/uploads/528d1f388f19c7922d3d933fb41d10aa/c02_Ibrahym_01.zip)

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Jun 29, 2023, 13:10

added #450 as child task

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Jun 29, 2023, 13:12

added #451 as child task

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Jun 30, 2023, 16:08

added #453 as child task

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Jul 6, 2023, 09:17

added #454 as child task
