### ISSUE TITLE
Integrate Well object into Modflow 6 Model object

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#369]
In GitLab by @JoerivanEngelen on May 15, 2023, 17:58

The Well object currently has to be special-cased in the Model's ``write`` and ``dump`` methods, as at present this is the only Package object which is grid agnostic, and for which the ``to_grid`` function has to be called.

Script to generate ``Well`` object to test with and do some stuff:

[test_lowlvl_wel.py](https://gitlab.com/deltares/imod/imod-python/uploads/db67b84abec475cbe8c7434ee42d7f9a/test_lowlvl_wel.py)

### Tasks
- [ ] https://github.com/Deltares/imod-python/issues/386
- [ ] https://github.com/Deltares/imod-python/issues/387
- [ ] https://github.com/Deltares/imod-python/issues/388
- [ ] https://github.com/Deltares/imod-python/issues/430
- [ ] https://github.com/Deltares/imod-python/issues/431
- [ ] https://github.com/Deltares/imod-python/issues/432
- [ ] https://github.com/Deltares/imod-python/issues/433
- [ ] https://github.com/Deltares/imod-python/issues/448

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on May 22, 2023, 13:56

added #386 as child task

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on May 22, 2023, 14:06

added #387 as child task

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on May 22, 2023, 14:08

added #388 as child task

**Comment by Manangka** [comment]
In GitLab by @luitjansl on Jun 12, 2023, 17:21

added #430 as child task

**Comment by Manangka** [comment]
In GitLab by @luitjansl on Jun 13, 2023, 15:26

added #432 as child task

**Comment by Manangka** [comment]
In GitLab by @luitjansl on Jun 13, 2023, 17:56

added #433 as child task

**Comment by Manangka** [comment]
created branch [`369-integrate-well-object-into-modflow-6-model-object`](/deltares/imod/imod-python/-/compare/master...369-integrate-well-object-into-modflow-6-model-object) to address this issue

**Comment by Manangka** [comment]
added #448 as child task

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Jul 27, 2023, 11:11

With last task merged in: https://gitlab.com/deltares/imod/imod-python/-/merge_requests/247

This user story can be closed!
