### ISSUE TITLE
Issues present in disv_converter example

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#471]
In GitLab by @JoerivanEngelen on Jul 14, 2023, 14:12

[See the issues present here](https://gitlab.com/deltares/imod/imod-python/-/merge_requests/240/diffs)

### Tasks
- [ ] https://github.com/Deltares/imod-python/issues/472
- [ ] https://github.com/Deltares/imod-python/issues/473
- [ ] https://github.com/Deltares/imod-python/issues/474
- [ ] https://github.com/Deltares/imod-python/issues/475
- [ ] https://github.com/Deltares/imod-python/issues/476

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Jul 14, 2023, 14:14

added #472 as child task

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Jul 14, 2023, 14:16

added #473 as child task

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Jul 14, 2023, 14:17

added #474 as child task

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Jul 14, 2023, 14:18

added #475 as child task

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Jul 14, 2023, 14:19

added #476 as child task

**Comment by JoerivanEngelen** [comment]
The disv_converter is likely going to be removed in v1.0.
