### ISSUE TITLE
review comments backwards compatibility branch

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#511]
In GitLab by @luitjansl on Aug 17, 2023, 14:07

The backwards compatibility feature branch was reviewed by @Huite  before its merge to master. A number comments could be processed following the usual procedure, but some comments would take more time to address. These will have their own task under this issue.

### Tasks
- [ ] https://github.com/Deltares/imod-python/issues/512
- [x] https://github.com/Deltares/imod-python/issues/515
- [x] https://github.com/Deltares/imod-python/issues/516
- [x] https://github.com/Deltares/imod-python/issues/517

**Comment by Manangka** [comment]
In GitLab by @luitjansl on Aug 17, 2023, 14:14

added #512 as child task

**Comment by Manangka** [comment]
In GitLab by @luitjansl on Aug 18, 2023, 12:20

added #515 as child task

**Comment by Manangka** [comment]
In GitLab by @luitjansl on Aug 21, 2023, 11:00

added #517 as child task

**Comment by Manangka** [comment]
In GitLab by @JoerivanEngelen on Aug 25, 2023, 11:20

marked this issue as related to #518
