### ISSUE TITLE
Clip_box_packages() passes wrong arguments to wel package clip_box()

### ISSUE THREAD

**Issue by Manangka** [Deltares/imod-python#626]
In GitLab by @HendrikKok on Nov 7, 2023, 10:27

_clip_box_packages() in model.py passes ‘layer_min’ and ‘layer_max’ as arguments. The package clip_box of well-class expects ‘z_min’ and ‘z_max’.

Pragmatic solution:

* Special-case gridagnostic packages (HFB non layered, WEL)
* Find z_min and z_max based on layer_min and layer_max in DIS package
* Provide that to clip_box
 
This requires the following refactoring/addition:

* The grid agnostic packages should accept layer_min and layer_max scalar values. ``cellids`` are determined in the function and consequently filtered whether they exceed layer_min and layer_max.

### Tasks
- [x] https://github.com/Deltares/imod-python/issues/681
- [x] https://github.com/Deltares/imod-python/issues/682
- [x] https://github.com/Deltares/imod-python/issues/684
- [ ] #740

**Comment by Manangka** [comment]
added #682 as child task

**Comment by Manangka** [comment]
added #684 as child task
